name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-project:
    name: Build .exe for windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src

      - uses: actions/upload-artifact@v2
        with:
          name: my-exe
          path: src/dist/windows # or path/to/artifact
  
  release-project:
    name: Release windows .exe
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "src/dist/windows/my-exe"
          tag: v${{ github.run_number }}
          name: Release V${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
